### ISSUE TITLE
Setting `httpreq_http_timeout` and `httpreq_propagation_timeout` config causes charm error

### ISSUE THREAD

**Issue by mthaddon** [canonical/httprequest-lego-k8s-operator#66]
#### Describe the bug

If you set `httpreq_http_timeout` and `httpreq_propagation_timeout` it causes a charm error on certificate creation.

#### To Reproduce

1. Deploy httprequest-lego-k8s
2. Configure values for `httpreq_http_timeout` and `httpreq_propagation_timeout` 
3. Relate it to a workload charm, like traefik-k8s.

#### Expected behavior

The charm doesn't error.

#### Screenshots

N/A

#### Logs

```
2024-02-27T08:15:10.631Z [container-agent] 2024-02-27 08:15:10 ERROR juju-log certificates:98: Uncaught exception while in charm code:
2024-02-27T08:15:10.631Z [container-agent] Traceback (most recent call last):
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/./src/charm.py", line 112, in <module>
2024-02-27T08:15:10.631Z [container-agent]     main(HTTPRequestLegoK8s)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/main.py", line 436, in main
2024-02-27T08:15:10.631Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
2024-02-27T08:15:10.631Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 351, in emit
2024-02-27T08:15:10.631Z [container-agent]     framework._emit(event)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
2024-02-27T08:15:10.631Z [container-agent]     self._reemit(event_path)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
2024-02-27T08:15:10.631Z [container-agent]     custom_handler(event)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/lib/charms/tls_certificates_interface/v1/tls_certificates.py", line 1059, in _on_relation_changed
2024-02-27T08:15:10.631Z [container-agent]     self.on.certificate_creation_request.emit(
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 351, in emit
2024-02-27T08:15:10.631Z [container-agent]     framework._emit(event)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
2024-02-27T08:15:10.631Z [container-agent]     self._reemit(event_path)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/framework.py", line 942, in _reemit
2024-02-27T08:15:10.631Z [container-agent]     custom_handler(event)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/lib/charms/lego_base_k8s/v0/lego_client.py", line 213, in _on_certificate_creation_request
2024-02-27T08:15:10.631Z [container-agent]     if not self._execute_lego_cmd():
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/lib/charms/lego_base_k8s/v0/lego_client.py", line 167, in _execute_lego_cmd
2024-02-27T08:15:10.631Z [container-agent]     process = self._container.exec(
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/model.py", line 2688, in exec
2024-02-27T08:15:10.631Z [container-agent]     return self._pebble.exec(
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/pebble.py", line 2501, in exec
2024-02-27T08:15:10.631Z [container-agent]     resp = self._request('POST', '/v1/exec', body=body)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/pebble.py", line 1655, in _request
2024-02-27T08:15:10.631Z [container-agent]     response = self._request_raw(method, path, query, headers, data)
2024-02-27T08:15:10.631Z [container-agent]   File "/var/lib/juju/agents/unit-httprequest-lego-k8s-0/charm/venv/ops/pebble.py", line 1701, in _request_raw
2024-02-27T08:15:10.631Z [container-agent]     raise APIError(body, code, status, message) from None
2024-02-27T08:15:10.631Z [container-agent] ops.pebble.APIError: cannot decode request body: json: cannot unmarshal number into Go struct field execPayload.environment of type string
```

#### Environment

- Charm / library version (if relevant): latest/stable revision 7
- Juju version (output from `juju --version`): 3.1.6
- Cloud Environment: OpenStack
- Kubernetes version (output from `kubectl version --short`): v1.28.7

#### Additional context

N/A

**Comment by gruyaume** [comment]
Fixed by #68
